# Generated by Django 6.0.1 on 2026-02-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='COURSES', to='Common.department')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyRegistration',
            fields=[
                ('faculty_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FACULTY', to='Common.department')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='qndisplay/')),
                ('year', models.IntegerField()),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QUESTION_BANK', to='Common.course')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=30)),
                ('quiz_name', models.CharField(max_length=40)),
                ('pass_mark', models.IntegerField()),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QUESTIONS', to='Common.questionbank')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('is_mock', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='Common.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Common.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('explananation', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='Common.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Common.quizattempt')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.quizoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Common.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('roll_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='STUDENTS', to='Common.department')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RESULTS', to='Common.studentregistration')),
            ],
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='Common.studentregistration'),
        ),
        migrations.CreateModel(
            name='FeedbackAndNotification',
            fields=[
                ('notification_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=100)),
                ('send', models.CharField(max_length=30)),
                ('receive', models.CharField(max_length=30)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FEEDBACKS', to='Common.facultyregistration')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FEEDBACKS', to='Common.studentregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SUBJECTS', to='Common.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SUBJECTS', to='Common.department')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QUESTIONS', to='Common.subject'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QUESTION_BANK', to='Common.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'student', 'is_mock')},
        ),
    ]
