# Generated by Django 5.2.8 on 2025-11-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_registration',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=30, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty_registration',
            fields=[
                ('faculty_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('department_name', models.CharField(max_length=30)),
                ('faculty_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='question_bank',
            fields=[
                ('course_name', models.CharField(max_length=30, unique=True)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('quiz_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=30, unique=True)),
                ('correct_option', models.CharField(max_length=300)),
                ('option_A', models.CharField(max_length=300)),
                ('option_B', models.CharField(max_length=300)),
                ('option_C', models.CharField(max_length=300)),
                ('option_D', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='student_registration',
            fields=[
                ('roll_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('email_id', models.EmailField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=30)),
                ('subject_k', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='QUESTIONS', to='Common.question_bank')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('correct_answer', models.IntegerField()),
                ('wrong_answer', models.IntegerField()),
                ('remarks', models.CharField(max_length=20)),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RESULTS', to='Common.student_registration')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_and_notification',
            fields=[
                ('summary', models.CharField(max_length=100)),
                ('notification_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('send', models.CharField(max_length=30)),
                ('receive', models.CharField(max_length=30)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FEEDBACKS', to='Common.faculty_registration')),
                ('roll_no', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FEEDBACKS', to='Common.student_registration')),
            ],
        ),
    ]
