# Generated by Django 5.2.8 on 2025-11-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='Difficulty_Level',
            field=models.CharField(blank=True, default='easy', max_length=300, null=True),
        ),
    ]
