# Generated by Django 6.0.1 on 2026-02-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRegistration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_bank',
        ),
    ]
