# Generated by Django 5.2.8 on 2025-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_department_quiz_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionupload',
            field=models.FileField(default=4, upload_to='qndisplay2'),
            preserve_default=False,
        ),
    ]
