# Generated by Django 6.0.2 on 2026-02-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_delete_adminregistration_remove_quiz_question_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstrator',
            fields=[
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
