# Generated by Django 6.0.2 on 2026-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_adminstrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyregistration',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
