# Generated by Django 5.2.4 on 2025-12-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_questions_questionupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.CharField(default=2, max_length=300),
            preserve_default=False,
        ),
    ]
