# Generated by Django 5.2.8 on 2025-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_bank',
            name='course_name',
            field=models.CharField(max_length=30),
        ),
    ]
