# Generated by Django 5.2.8 on 2025-12-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_alter_question_bank_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_registration',
            name='dptname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='STUDENTS', to='Common.department'),
        ),
    ]
