# Generated by Django 5.2.8 on 2025-12-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0006_student_registration_dptname'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty_registration',
            name='dptname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='FACULTY', to='Common.department'),
        ),
    ]
